import pandas as pd

city_mapping = {
    "THIRUBUVANAI(VILLIANUR)":"Pondicherry",
    "NATIONALISED SECTOR(TVPM) RTO":"",
  "ADOOR SRTO": "Pathanamthitta",
  "ALANGUDI UO": "Thanjavur",
  "ALANGULAM UO": "Tirunelveli",
  "ALAPPUZHA RTO": "Alappuzha",
  "ALATHUR SRTO": "Palakkad",
  "ALUVA SRTO": "Ernakulam",
  "AMBASAMUTHIRAM UO": "Tirunelveli",
  "AMBATTUR RTO": "Chennai",
  "AMBUR UO": "Vellore",
  "ANGAMALI SRTO": "Ernakulam",
  "ARAKKONAM UO": "Vellore",
  "ARANI RTO": "Vellore",
  "ARANTHANGI UO": "Thanjavur",
  "ARAVAKURICHI UO": "Salem",
  "ARIYALUR RTO": "Tiruchirapalli",
  "ARUPPUKOTTAI UO": "Madurai",
  "ATHANI ARTO": "Belgaum",
  "ATTINGAL RTO": "Thiruvananthapuram",
  "ATTUR RTO": "Salem",
  "AVINASHI UO": "Coimbatore",
  "BAGALKOT  RTO": "Bijapur",
  "BAHOUR": "Pondicherry",
  "BAILHONGAL  RTO": "Belgaum",
  "BANTWALA ARTO": "Mangalore",
  "BASAVAKALYAN ARTO": "Kalaburagi",
  "BATLAGUNDU UO": "Tiruchirapalli",
  "BELLARY  RTO": "Bellary",
  "BENGALURU CENTRAL  RTO": "Bangalore",
  "BENGALURU EAST  RTO": "Bangalore",
  "BENGALURU NORTH  RTO": "Bangalore",
  "BENGALURU SOUTH  RTO": "Bangalore",
  "BENGALURU WEST  RTO": "Bangalore",
  "BHALKI  ARTO": "Kalaburagi",
  "BHAVANI UO": "Erode",
  "BIDAR  RTO": "Kalaburagi",
  "BIJAPUR  RTO": "Bijapur",
  "CHADAYAMANGALA SRTO": "Kollam",
  "CHALAKKUDY SRTO": "Thrissur",
  "CHAMARAJANAGAR  RTO": "Mysore",
  "CHANDAPURA, BENGALURU RTO": "Bangalore",
  "CHANGANACHERRY SRTO": "Kottayam",
  "CHENGALPATTU RTO": "Chennai",
  "CHENGANNUR SRTO": "Kayamkulam",
  "CHENNAI (CENTRAL) RTO": "Chennai",
  "CHENNAI (EAST) RTO": "Chennai",
  "CHENNAI (NORTH) RTO": "Chennai",
  "CHENNAI (NORTH-EAST) RTO": "Chennai",
  "CHENNAI (SOUTH) RTO": "Chennai",
  "CHENNAI (SOUTH-EAST) RTO": "Chennai",
  "CHENNAI (SOUTH-WEST) RTO": "Chennai",
  "CHENNAI (WEST) RTO": "Chennai",
  "CHERTHALA SRTO": "Alappuzha",
  "CHEYYAR UO": "Vellore",
  "CHICKABALLAPUR  RTO": "Chikkaballapur",
  "CHIDAMBARAM RTO": "Cuddalore",
  "CHIKAMANGLUR RTO": "Mangalore",
  "CHIKKODI  RTO": "Belgaum",
  "CHINTAMANI ARTO": "Chikkaballapur",
  "CHITRADURGA  RTO": "Tumkur",
  "CHITTUR SRTO": "Palakkad",
  "COIMBATORE (CENTRAL) RTO": "Coimbatore",
  "COIMBATORE (NORTH) RTO": "Coimbatore",
  "COIMBATORE (SOUTH) RTO": "Coimbatore",
  "COIMBATORE (WEST) RTO": "Coimbatore",
  "CUDDALORE RTO": "Cuddalore",
  "DANDELI ARTO": "Hubli",
  "DAVANAGERE  RTO": "Davanagere",
  "DEVANAHALLI  ARTO": "Bangalore",
  "DEVIKULAM SRTO": "Ernakulam",
  "DHARAPURAM RTO": "Coimbatore",
  "DHARMAPURI RTO": "Hosur",
  "DHARWAD EAST RTO": "Hubli",
  "DHARWAD WEST RTO": "Hubli",
  "DINDIGUL RTO": "Tiruchirapalli",
  "ELECTRONIC CITY  RTO": "Bangalore",
  "ERNAKULAM RTO": "Ernakulam",
  "ERODE (WEST) RTO": "Erode",
  "ERODE RTO": "Erode",
  "GADAG  RTO": "Hubli",
  "GINGEE UO": "Cuddalore",
  "GOKAK  ARTO": "Belgaum",
  "GOPICHETTIPALAYAM RTO": "Erode",
  "GUDALORE UO": "Coimbatore",
  "GUDIYATHAM UO": "Vellore",
  "GUMMIDIPOONDI UO": "Chennai",
  "GURUVAYUR SRTO": "Thrissur",
  "HARUR UO": "Hosur",
  "HASSAN  RTO": "Hassan",
  "HAVERI  RTO": "Hubli",
  "HONNAVAR  ARTO": "Murudeswar",
  "HOSPET  RTO": "Bellary",
  "HOSUR RTO": "Hosur",
  "HUNSUR  ARTO": "Mysore",
  "IDUKKI RTO": "Ernakulam",
  "ILLUPPUR UO": "Thanjavur",
  "IRINJALAKUDA SRTO": "Thrissur",
  "IRITTY SRTO": "Kannur",
  "JAMKHANDI  ARTO": "Bijapur",
  "JNANABHARATHI  RTO": "Bangalore",
  "K G F  ARTO": "Bangalore",
  "KALABURAGI  RTO": "Kalaburagi",
  "KALLAKURICHI RTO": "Cuddalore",
  "KANCHEEPURAM RTO": "Vellore",
  "KANGEYAM UO": "Coimbatore",
  "KANHANGAD SRTO": "Kannur",
  "KANJIRAPPALLY SRTO": "Kottayam",
  "KANNUR RTO": "Kannur",
  "KARAIKAL": "Pondicherry",
  "KARAIKUDI UO": "Madurai",
  "KARUNAGAPPALLY SRTO": "Kollam",
  "KARUR RTO": "Salem",
  "KARWAR  RTO": "Karwar",
  "KASARGODE RTO": "Kannur",
  "KATTAKADA SRTO": "Thiruvananthapuram",
  "KAYAMKULAM SRTO": "Kayamkulam",
  "KAZHAKUTTOM SRTO": "Thiruvananthapuram",
  "KODUNGALLUR SRTO": "Thrissur",
  "KODUVALLY SRTO": "Kozhikode",
  "KOILANDY SRTO": "Kozhikode",
  "KOLAR  RTO": "Bangalore",
  "KOLLAM RTO": "Kollam",
  "KONDOTTY SRTO": "Malappuram",
  "KONNI SRTO": "Pathanamthitta",
  "KOPPAL  RTO": "Bellary",
  "KOTHAMANGALAM SRTO": "Ernakulam",
  "KOTTARAKKARA SRTO": "Kollam",
  "KOTTAYAM RTO": "Kottayam",
  "KOVILPATTI RTO": "Tirunelveli",
  "KOZHIKODE RTO": "Kozhikode",
  "KRISHNAGIRI RTO": "Hosur",
  "KRISHNARAJAPURAM  RTO": "Bangalore",
  "KULITHALI UO": "Salem",
  "KUMARAPALAYAM RTO": "Salem",
  "KUMBAKONAM RTO": "Thanjavur",
  "KUNDRATHUR RTO": "Chennai",
  "KUNNATHUR SRTO": "Kollam",
  "KUTTANADU SRTO": "Alappuzha",
  "LALKUDI UO": "Tiruchirapalli",
  "MADHUGIRI, TUMAKURU ARTO": "Tumkur",
  "MADIKERI  RTO": "Mysore",
  "MADURAI (CENTRAL) RTO": "Madurai",
  "MADURAI (NORTH) RTO": "Madurai",
  "MADURAI (SOUTH) RTO": "Madurai",
  "MADURANTAGAM UO": "Chennai",
  "MAHE": "Pondicherry",
  "MALAPPURAM RTO": "Malappuram",
  "MALLAPPALLY SRTO": "Pathanamthitta",
  "MANANTHAVADY SRTO": "Wayanad",
  "MANAPARAI UO": "Tiruchirapalli",
  "MANDYA  RTO": "Mysore",
  "MANGALORE  RTO": "Mangalore",
  "MANMANGALAM UO": "Salem",
  "MANNARGHAT SRTO": "Palakkad",
  "MANNARGUDI UO": "Thanjavur",
  "MARTHANDAM RTO": "Nagercoil",
  "MATTANCHERRY SRTO": "Ernakulam",
  "MAVELIKKARA SRTO": "Alappuzha",
  "MAYILADUTHURAI RTO": "Thanjavur",
  "MEENAMBAKKAM RTO": "Chennai",
  "MELUR UO": "Madurai",
  "METTUPALAYAM RTO": "Coimbatore",
  "METTUR RTO": "Salem",
  "MUSURI UO": "Tiruchirapalli",
  "MUVATTUPUZHA RTO": "Ernakulam",
  "MYSURU  EAST  RTO": "Mysore",
  "MYSURU WEST  RTO": "Mysore",
  "NAGAMANGALA  RTO": "Mysore",
  "NAGAPATTINAM RTO": "Thanjavur",
  "NAGERCOIL RTO": "Nagercoil",
  "NAMAKKAL (NORTH) RTO": "Salem",
  "NAMAKKAL (SOUTH) RTO": "Salem",
  "NANMANDA SRTO": "Kozhikode",
  "NATHAM UO": "Tiruchirapalli",
  "NEDUMANGADU SRTO": "Thiruvananthapuram",
  "NELAMANGALA  RTO": "Bangalore",
  "NEYVELI UO": "Cuddalore",
  "NEYYATTINKARA SRTO": "Thiruvananthapuram",
  "NILAMBUR SRTO": "Malappuram",
  "NORTH PARUR SRTO": "Ernakulam",
  "ODDANCHATRAM  UO": "Tiruchirapalli",
  "OMALURE UO": "Salem",
  "OOTY RTO": "Coimbatore",
  "OTTAPPALAM SRTO": "Palakkad",
  "OULGARET": "Pondicherry",
  "PALACODE UO": "Hosur",
  "PALAI SRTO": "Kottayam",
  "PALAKKAD RTO": "Palakkad",
  "PALANI RTO": "Tiruchirapalli",
  "PANRUTI UO": "Cuddalore",
  "PARAMAKUDI UO": "Madurai",
  "PARAMATHI VELLURE UO": "Salem",
  "PARASSALA SRTO": "Thiruvananthapuram",
  "PATHANAMTHITTA RTO": "Pathanamthitta",
  "PATHANAPURAM SRTO": "Kollam",
  "PATTAMBI SRTO": "Palakkad",
  "PATTUKOTTAI UNIT OFFICE": "Thanjavur",
  "PAYYANNUR SRTO": "Kannur",
  "PERAMBALUR RTO": "Tiruchirapalli",
  "PERAMBRA SRTO": "Kozhikode",
  "PERINTHALMANNA SRTO": "Perinthalmana",
  "PERUMBAVUR SRTO": "Ernakulam",
  "PERUNDURAI RTO": "Erode",
  "POLLACHI RTO": "Coimbatore",
  "PONNANI SRTO": "Malappuram",
  "POONAMALLEE RTO": "Chennai",
  "PUDUCHERRY": "Pondicherry",
  "PUDUKOTTAI RTO": "Thanjavur",
  "PUNALUR SRTO": "Kollam",
  "PUTTUR  RTO": "Mangalore",
  "RAICHUR  RTO": "Bellary",
  "RAJAPALAYAM UO": "Madurai",
  "RAMANAGAR  RTO": "Bangalore",
  "RAMANATHAPURAM RTO": "Madurai",
  "RAMANATTUKARA (FEROKE) SRTO": "Kozhikode",
  "RAMDURGA ARTO": "Belgaum",
  "RANIBENNUR ARTO": "Hubli",
  "RANIPET RTO": "Vellore",
  "RANNI SRTO": "Pathanamthitta",
  "RASIPURAM UO": "Salem",
  "REDHILLS RTO": "Chennai",
  "REGIONAL TRANSPORT OFFICE BELAGAVI": "Belgaum",
  "RTO CHENNAI (NORTH WEST)": "Chennai",
  "SAGAR  ARTO": "Shimoga",
  "SAKALESHPURA  ARTO": "Mangalore",
  "SALEM (EAST) RTO": "Salem",
  "SALEM (SOUTH) RTO": "Salem",
  "SALEM (WEST) RTO": "Salem",
  "SANKAGIRI RTO": "Salem",
  "SANKARANKOVIL RTO": "Tirunelveli",
  "SATHYAMANGALAM UO": "Erode",
  "SHIMOGA  RTO": "Shimoga",
  "SHOLINGANALLUR RTO": "Chennai",
  "STU AND AUTORIKSHAW,  SHANTHINAGAR RTO": "Bangalore",
  "SIRKALI UO": "Thanjavur",
  "SIRSI  RTO": "Hubli",
  "SIVAGANGAI RTO": "Madurai",
  "SIVAKASI RTO": "Madurai",
  "SRIPERUMBUDUR RTO": "Chennai",
  "SRIRANGAM RTO": "Tiruchirapalli",
  "SRIVILLIPUTHUR RTO": "Madurai",
  "SULTHANBATHERY SRTO": "Wayanad",
  "SULUR UO": "Coimbatore",
  "TAMBARAM RTO": "Chennai",
  "TARIKERE, CHIKKAMAGALURU ARTO": "Mangalore",
  "TENKASI RTO": "Tirunelveli",
  "THALASSERY SRTO": "Kannur",
  "THALIPARAMBA SRTO": "Kannur",
  "THANJAVUR RTO": "Thanjavur",
  "THENI RTO": "Madurai",
  "THIRUCHENDUR RTO": "Tirunelveli",
  "THIRUKALUKUNTRAM UO": "Chennai",
  "THIRUMANGALAM  UO": "Madurai",
  "THIRUPATTUR RTO": "Vellore",
  "THIRUR SRTO": "Malappuram",
  "THIRURANGADI SRTO": "Malappuram",
  "THIRUBUVANAI(VILLIANUR)": "Pondicherry",
  "THIRUTHURAIPOONDI UO": "Thanjavur",
  "THIRUTTANI UO": "Chennai",
  "THIRUVALLA SRTO": "Pathanamthitta",
  "THODUPUZHA SRTO": "Ernakulam",
  "THOOTHUKUDI RTO": "Tirunelveli",
  "THRIPRAYAR SRTO": "Thrissur",
  "THRISSUR RTO": "Thrissur",
  "THURAIYUR UO": "Tiruchirapalli",
  "TINDIVANAM RTO": "Cuddalore",
  "TIPTUR  ARTO": "Tumkur",
  "TIRUCHENGODE RTO": "Salem",
  "TIRUCHI RTO": "Tiruchirapalli",
  "TIRUCHI(EAST) RTO": "Tiruchirapalli",
  "TIRUNELVELI RTO": "Tirunelveli",
  "TIRUPPUR (NORTH) RTO": "Tirupur",
  "TIRUPPUR (SOUTH) RTO": "Tirupur",
  "TIRUVALLUR RTO": "Chennai",
  "TIRUVANNAMALAI RTO": "Vellore",
  "TIRUVARUR RTO": "Thanjavur",
  "TIRUVERANBUR UO": "Tiruchirapalli",
  "TRIPUNITHURA SRTO": "Ernakulam",
  "TRIVANDRUM RTO": "Thiruvananthapuram",
  "TUMKUR  RTO": "Tumkur",
  "UDUMALPET RTO": "Coimbatore",
  "UDUMBANCHOLA SRTO": "Ernakulam",
  "UDUPI  RTO": "Mangalore",
  "ULUNDURPET RTO": "Cuddalore",
  "USILAMPATTI UO": "Madurai",
  "UTHAMAPALAYAM UO": "Madurai",
  "UZHAVOOR SRTO": "Kottayam",
  "VADAKARA RTO": "Kozhikode",
  "VADIPATTI UO": "Madurai",
  "VAIKOM SRTO": "Kottayam",
  "VALAPPADI UO": "Salem",
  "VALLIYUR UO": "Tirunelveli",
  "VALPARAI UO": "Coimbatore",
  "VANDIPERIYAR SRTO": "Ernakulam",
  "VANIYAMBADI RTO": "Vellore",
  "VARKALA SRTO": "Thiruvananthapuram",
  "VEDACHANDUR UO": "Tiruchirapalli",
  "VELLARIKUNDU SRTO": "Kannur",
  "VELLORE RTO": "Vellore",
  "VILLIANUR": "Pondicherry",
  "VILUPPURAM RTO": "Cuddalore",
  "VIRUDHACHALAM UO": "Cuddalore",
  "VIRUDHUNAGAR RTO": "Madurai",
  "WADAKKANCHERRY SRTO": "Thrissur",
  "WAYANAD RTO": "Wayanad",
  "YADGIRI  RTO": "Kalaburagi",
  "YALAHANKA  RTO": "Bangalore",
  "YANAM": "Pondicherry"
}

rto_ao_mapping = {
        "THIRUBUVANAI(VILLIANUR)":"RO South2",
    "NATIONALISED SECTOR(TVPM) RTO":"",
  "ADOOR SRTO": "RO South3",
  "ALANGUDI UO": "Thanjavur",
  "ALANGULAM UO": "Tirunelveli",
  "ALAPPUZHA RTO": "RO South3",
  "ALATHUR SRTO": "RO South3",
  "ALUVA SRTO": "RO South3",
  "AMBASAMUTHIRAM UO": "Tirunelveli",
  "AMBATTUR RTO": "RO South2",
  "AMBUR UO": "RO South2",
  "ANGAMALI SRTO": "RO South3",
  "ARAKKONAM UO": "RO South2",
  "ARANI RTO": "RO South2",
  "ARANTHANGI UO": "Thanjavur",
  "ARAVAKURICHI UO": "RO South2",
  "ARIYALUR RTO": "Tiruchirappalli",
  "ARUPPUKOTTAI UO": "Madurai",
  "ATHANI ARTO": "RO South1",
  "ATTINGAL RTO": "RO South3",
  "ATTUR RTO": "RO South2",
  "AVINASHI UO": "Coimbatore",
  "BAGALKOT  RTO": "RO South1",
  "BAHOUR": "RO South2",
  "BAILHONGAL  RTO": "RO South1",
  "BANTWALA ARTO": "Mangalore",
  "BASAVAKALYAN ARTO": "RO South1",
  "BATLAGUNDU UO": "Tiruchirappalli",
  "BELLARY  RTO": "RO South1",
  "BENGALURU CENTRAL  RTO": "RO South1",
  "BENGALURU EAST  RTO": "RO South1",
  "BENGALURU NORTH  RTO": "RO South1",
  "BENGALURU SOUTH  RTO": "RO South1",
  "BENGALURU WEST  RTO": "RO South1",
  "BHALKI  ARTO": "RO South1",
  "BHAVANI UO": "RO South2",
  "BIDAR  RTO": "RO South1",
  "BIJAPUR  RTO": "RO South1",
  "CHADAYAMANGALA SRTO": "RO South3",
  "CHALAKKUDY SRTO": "RO South3",
  "CHAMARAJANAGAR  RTO": "RO South1",
  "CHANDAPURA, BENGALURU RTO": "RO South1",
  "CHANGANACHERRY SRTO": "RO South3",
  "CHENGALPATTU RTO": "RO South2",
  "CHENGANNUR SRTO": "RO South3",
  "CHENNAI (CENTRAL) RTO": "RO South2",
  "CHENNAI (EAST) RTO": "RO South2",
  "CHENNAI (NORTH) RTO": "RO South2",
  "CHENNAI (NORTH-EAST) RTO": "RO South2",
  "CHENNAI (SOUTH) RTO": "RO South2",
  "CHENNAI (SOUTH-EAST) RTO": "RO South2",
  "CHENNAI (SOUTH-WEST) RTO": "RO South2",
  "CHENNAI (WEST) RTO": "RO South2",
  "CHERTHALA SRTO": "RO South3",
  "CHEYYAR UO": "RO South2",
  "CHICKABALLAPUR  RTO": "RO South1",
  "CHIDAMBARAM RTO": "RO South2",
  "CHIKAMANGLUR RTO": "Mangalore",
  "CHIKKODI  RTO": "RO South1",
  "CHINTAMANI ARTO": "RO South1",
  "CHITRADURGA  RTO": "RO South1",
  "CHITTUR SRTO": "RO South3",
  "COIMBATORE (CENTRAL) RTO": "Coimbatore",
  "COIMBATORE (NORTH) RTO": "Coimbatore",
  "COIMBATORE (SOUTH) RTO": "Coimbatore",
  "COIMBATORE (WEST) RTO": "Coimbatore",
  "CUDDALORE RTO": "RO South2",
  "DANDELI ARTO": "RO South1",
  "DAVANAGERE  RTO": "RO South1",
  "DEVANAHALLI  ARTO": "RO South1",
  "DEVIKULAM SRTO": "RO South3",
  "DHARAPURAM RTO": "Coimbatore",
  "DHARMAPURI RTO": "RO South2",
  "DHARWAD EAST RTO": "RO South1",
  "DHARWAD WEST RTO": "RO South1",
  "DINDIGUL RTO": "Tiruchirappalli",
  "ELECTRONIC CITY  RTO": "RO South1",
  "ERNAKULAM RTO": "RO South3",
  "ERODE (WEST) RTO": "RO South2",
  "ERODE RTO": "RO South2",
  "GADAG  RTO": "RO South1",
  "GINGEE UO": "RO South2",
  "GOKAK  ARTO": "RO South1",
  "GOPICHETTIPALAYAM RTO": "RO South2",
  "GUDALORE UO": "Coimbatore",
  "GUDIYATHAM UO": "RO South2",
  "GUMMIDIPOONDI UO": "RO South2",
  "GURUVAYUR SRTO": "RO South3",
  "HARUR UO": "RO South2",
  "HASSAN  RTO": "Mangalore",
  "HAVERI  RTO": "RO South1",
  "HONNAVAR  ARTO": "RO South1",
  "HOSPET  RTO": "RO South1",
  "HOSUR RTO": "RO South2",
  "HUNSUR  ARTO": "RO South1",
  "IDUKKI RTO": "RO South3",
  "ILLUPPUR UO": "Thanjavur",
  "IRINJALAKUDA SRTO": "RO South3",
  "IRITTY SRTO": "Kannur",
  "JAMKHANDI  ARTO": "RO South1",
  "JNANABHARATHI  RTO": "RO South1",
  "K G F  ARTO": "RO South1",
  "KALABURAGI  RTO": "RO South1",
  "KALLAKURICHI RTO": "RO South2",
  "KANCHEEPURAM RTO": "RO South2",
  "KANGEYAM UO": "Coimbatore",
  "KANHANGAD SRTO": "Kannur",
  "KANJIRAPPALLY SRTO": "RO South3",
  "KANNUR RTO": "Kannur",
  "KARAIKAL": "RO South2",
  "KARAIKUDI UO": "Madurai",
  "KARUNAGAPPALLY SRTO": "RO South3",
  "KARUR RTO": "RO South2",
  "KARWAR  RTO": "RO South1",
  "KASARGODE RTO": "Kannur",
  "KATTAKADA SRTO": "RO South3",
  "KAYAMKULAM SRTO": "RO South3",
  "KAZHAKUTTOM SRTO": "RO South3",
  "KODUNGALLUR SRTO": "RO South3",
  "KODUVALLY SRTO": "Kozhikode",
  "KOILANDY SRTO": "Kozhikode",
  "KOLAR  RTO": "RO South1",
  "KOLLAM RTO": "RO South3",
  "KONDOTTY SRTO": "RO South3",
  "KONNI SRTO": "RO South3",
  "KOPPAL  RTO": "RO South1",
  "KOTHAMANGALAM SRTO": "RO South3",
  "KOTTARAKKARA SRTO": "RO South3",
  "KOTTAYAM RTO": "RO South3",
  "KOVILPATTI RTO": "Tirunelveli",
  "KOZHIKODE RTO": "Kozhikode",
  "KRISHNAGIRI RTO": "RO South2",
  "KRISHNARAJAPURAM  RTO": "RO South1",
  "KULITHALI UO": "RO South2",
  "KUMARAPALAYAM RTO": "RO South2",
  "KUMBAKONAM RTO": "Thanjavur",
  "KUNDRATHUR RTO": "RO South2",
  "KUNNATHUR SRTO": "RO South3",
  "KUTTANADU SRTO": "RO South3",
  "LALKUDI UO": "Tiruchirappalli",
  "MADHUGIRI, TUMAKURU ARTO": "RO South1",
  "MADIKERI  RTO": "RO South1",
  "MADURAI (CENTRAL) RTO": "Madurai",
  "MADURAI (NORTH) RTO": "Madurai",
  "MADURAI (SOUTH) RTO": "Madurai",
  "MADURANTAGAM UO": "RO South2",
  "MAHE": "RO South2",
  "MALAPPURAM RTO": "RO South3",
  "MALLAPPALLY SRTO": "RO South3",
  "MANANTHAVADY SRTO": "Kozhikode",
  "MANAPARAI UO": "Tiruchirappalli",
  "MANDYA  RTO": "RO South1",
  "MANGALORE  RTO": "Mangalore",
  "MANMANGALAM UO": "RO South2",
  "MANNARGHAT SRTO": "RO South3",
  "MANNARGUDI UO": "Thanjavur",
  "MARTHANDAM RTO": "Kanyakumari",
  "MATTANCHERRY SRTO": "RO South3",
  "MAVELIKKARA SRTO": "RO South3",
  "MAYILADUTHURAI RTO": "Thanjavur",
  "MEENAMBAKKAM RTO": "RO South2",
  "MELUR UO": "Madurai",
  "METTUPALAYAM RTO": "Coimbatore",
  "METTUR RTO": "RO South2",
  "MUSURI UO": "Tiruchirappalli",
  "MUVATTUPUZHA RTO": "RO South3",
  "MYSURU  EAST  RTO": "RO South1",
  "MYSURU WEST  RTO": "RO South1",
  "NAGAMANGALA  RTO": "RO South1",
  "NAGAPATTINAM RTO": "Thanjavur",
  "NAGERCOIL RTO": "Kanyakumari",
  "NAMAKKAL (NORTH) RTO": "RO South2",
  "NAMAKKAL (SOUTH) RTO": "RO South2",
  "NANMANDA SRTO": "Kozhikode",
  "NATHAM UO": "Tiruchirappalli",
  "NEDUMANGADU SRTO": "RO South3",
  "NELAMANGALA  RTO": "RO South1",
  "NEYVELI UO": "RO South2",
  "NEYYATTINKARA SRTO": "RO South3",
  "NILAMBUR SRTO": "RO South3",
  "NORTH PARUR SRTO": "RO South3",
  "ODDANCHATRAM  UO": "Tiruchirappalli",
  "OMALURE UO": "RO South2",
  "OOTY RTO": "Coimbatore",
  "OTTAPPALAM SRTO": "RO South3",
  "OULGARET": "RO South2",
  "PALACODE UO": "RO South2",
  "PALAI SRTO": "RO South3",
  "PALAKKAD RTO": "RO South3",
  "PALANI RTO": "Tiruchirappalli",
  "PANRUTI UO": "RO South2",
  "PARAMAKUDI UO": "Madurai",
  "PARAMATHI VELLURE UO": "RO South2",
  "PARASSALA SRTO": "RO South3",
  "PATHANAMTHITTA RTO": "RO South3",
  "PATHANAPURAM SRTO": "RO South3",
  "PATTAMBI SRTO": "RO South3",
  "PATTUKOTTAI UNIT OFFICE": "Thanjavur",
  "PAYYANNUR SRTO": "Kannur",
  "PERAMBALUR RTO": "Tiruchirappalli",
  "PERAMBRA SRTO": "Kozhikode",
  "PERINTHALMANNA SRTO": "Malappuram",
  "PERUMBAVUR SRTO": "RO South3",
  "PERUNDURAI RTO": "RO South2",
  "POLLACHI RTO": "Coimbatore",
  "PONNANI SRTO": "RO South3",
  "POONAMALLEE RTO": "RO South2",
  "PUDUCHERRY": "RO South2",
  "PUDUKOTTAI RTO": "Thanjavur",
  "PUNALUR SRTO": "RO South3",
  "PUTTUR  RTO": "Mangalore",
  "RAICHUR  RTO": "RO South1",
  "RAJAPALAYAM UO": "Madurai",
  "RAMANAGAR  RTO": "RO South1",
  "RAMANATHAPURAM RTO": "Madurai",
  "RAMANATTUKARA (FEROKE) SRTO": "Kozhikode",
  "RAMDURGA ARTO": "RO South1",
  "RANIBENNUR ARTO": "RO South1",
  "RANIPET RTO": "RO South2",
  "RANNI SRTO": "RO South3",
  "RASIPURAM UO": "RO South2",
  "REDHILLS RTO": "RO South2",
  "REGIONAL TRANSPORT OFFICE BELAGAVI": "RO South1",
  "RTO CHENNAI (NORTH WEST)": "RO South2",
  "SAGAR  ARTO": "RO South1",
  "SAKALESHPURA  ARTO": "Mangalore",
  "SALEM (EAST) RTO": "RO South2",
  "SALEM (SOUTH) RTO": "RO South2",
  "SALEM (WEST) RTO": "RO South2",
  "SANKAGIRI RTO": "RO South2",
  "SANKARANKOVIL RTO": "Tirunelveli",
  "SATHYAMANGALAM UO": "RO South2",
  "SHIMOGA  RTO": "RO South1",
  "SHOLINGANALLUR RTO": "RO South2",
  "SIRKALI UO": "Thanjavur",
  "SIRSI  RTO": "RO South1",
  "SIVAGANGAI RTO": "Madurai",
  "SIVAKASI RTO": "Madurai",
  "SRIPERUMBUDUR RTO": "RO South2",
  "SRIRANGAM RTO": "Tiruchirappalli",
  "SRIVILLIPUTHUR RTO": "Madurai",
  "STU AND AUTORIKSHAW,  SHANTHINAGAR RTO": "RO South1",
  "SULTHANBATHERY SRTO": "Kozhikode",
  "SULUR UO": "Coimbatore",
  "TAMBARAM RTO": "RO South2",
  "TARIKERE, CHIKKAMAGALURU ARTO": "Mangalore",
  "TENKASI RTO": "Tirunelveli",
  "THALASSERY SRTO": "Kannur",
  "THALIPARAMBA SRTO": "Kannur",
  "THANJAVUR RTO": "Thanjavur",
  "THENI RTO": "Madurai",
  "THIRUCHENDUR RTO": "Tirunelveli",
  "THIRUKALUKUNTRAM UO": "RO South2",
  "THIRUMANGALAM  UO": "Madurai",
  "THIRUPATTUR RTO": "RO South2",
  "THIRUR SRTO": "RO South3",
  "THIRURANGADI SRTO": "RO South3",
  "THIRUBUVANAI(VILLIANUR)": "RO South2",
  "THIRUTHURAIPOONDI UO": "Thanjavur",
  "THIRUTTANI UO": "RO South2",
  "THIRUVALLA SRTO": "RO South3",
  "THODUPUZHA SRTO": "RO South3",
  "THOOTHUKUDI RTO": "Tirunelveli",
  "THRIPRAYAR SRTO": "RO South3",
  "THRISSUR RTO": "RO South3",
  "THURAIYUR UO": "Tiruchirappalli",
  "TINDIVANAM RTO": "RO South2",
  "TIPTUR  ARTO": "RO South1",
  "TIRUCHENGODE RTO": "RO South2",
  "TIRUCHI RTO": "Tiruchirappalli",
  "TIRUCHI(EAST) RTO": "Tiruchirappalli",
  "TIRUNELVELI RTO": "Tirunelveli",
  "TIRUPPUR (NORTH) RTO": "Coimbatore",
  "TIRUPPUR (SOUTH) RTO": "Coimbatore",
  "TIRUVALLUR RTO": "RO South2",
  "TIRUVANNAMALAI RTO": "RO South2",
  "TIRUVARUR RTO": "Thanjavur",
  "TIRUVERANBUR UO": "Tiruchirappalli",
  "TRIPUNITHURA SRTO": "RO South3",
  "TRIVANDRUM RTO": "RO South3",
  "TUMKUR  RTO": "RO South1",
  "UDUMALPET RTO": "Coimbatore",
  "UDUMBANCHOLA SRTO": "RO South3",
  "UDUPI  RTO": "Mangalore",
  "ULUNDURPET RTO": "RO South2",
  "USILAMPATTI UO": "Madurai",
  "UTHAMAPALAYAM UO": "Madurai",
  "UZHAVOOR SRTO": "RO South3",
  "VADAKARA RTO": "Kozhikode",
  "VADIPATTI UO": "Madurai",
  "VAIKOM SRTO": "RO South3",
  "VALAPPADI UO": "RO South2",
  "VALLIYUR UO": "Tirunelveli",
  "VALPARAI UO": "Coimbatore",
  "VANDIPERIYAR SRTO": "RO South3",
  "VANIYAMBADI RTO": "RO South2",
  "VARKALA SRTO": "RO South3",
  "VEDACHANDUR UO": "Tiruchirappalli",
  "VELLARIKUNDU SRTO": "Kannur",
  "VELLORE RTO": "RO South2",
  "VILLIANUR": "RO South2",
  "VILUPPURAM RTO": "RO South2",
  "VIRUDHACHALAM UO": "RO South2",
  "VIRUDHUNAGAR RTO": "Madurai",
  "WADAKKANCHERRY SRTO": "RO South3",
  "WAYANAD RTO": "Kozhikode",
  "YADGIRI  RTO": "RO South1",
  "YALAHANKA  RTO": "RO South1",
  "YANAM": "RO South2"
}

cluster_mapping = {
    "THIRUBUVANAI(VILLIANUR)":"Pondicherry",
    "NATIONALISED SECTOR(TVPM) RTO":"",
  "ATHANI ARTO": "Belgaum",
  "BAGALKOT  RTO": "Bijapur",
  "BANTWALA ARTO": "Mangalore",
  "BASAVAKALYAN ARTO": "Kalaburagi",
  "BELLARY  RTO": "Hospet",
  "BENGALURU CENTRAL  RTO": "Bangalore",
  "BENGALURU EAST  RTO": "Bangalore",
  "BENGALURU NORTH  RTO": "Bangalore",
  "BENGALURU SOUTH  RTO": "Bangalore",
  "BENGALURU WEST  RTO": "Bangalore",
  "BHALKI  ARTO": "Kalaburagi",
  "BIDAR  RTO": "Kalaburagi",
  "BIJAPUR  RTO": "Bijapur",
  "CHAMARAJANAGAR  RTO": "Mysore",
  "CHANDAPURA, BENGALURU RTO": "Bangalore",
  "CHICKABALLAPUR  RTO": "Tumkur",
  "CHIKAMANGLUR RTO": "Mangalore",
  "CHIKKODI  RTO": "Belgaum",
  "CHITRADURGA  RTO": "Tumkur",
  "DAVANAGERE  RTO": "Shimoga",
  "DEVANAHALLI  ARTO": "Bangalore",
  "DHARWAD EAST RTO": "Hubli",
  "DHARWAD WEST RTO": "Hubli",
  "ELECTRONIC CITY  RTO": "Bangalore",
  "GADAG  RTO": "Hubli",
  "GOKAK  ARTO": "Belgaum",
  "HASSAN  RTO": "Mangalore",
  "HAVERI  RTO": "Hubli",
  "HONNAVAR  ARTO": "Hubli",
  "HOSPET  RTO": "Hospet",
  "HUNSUR  ARTO": "Mysore",
  "JAMKHANDI  ARTO": "Bijapur",
  "JNANABHARATHI  RTO": "Bangalore",
  "K G F  ARTO": "Bangalore",
  "KALABURAGI  RTO": "Kalaburagi",
  "KARWAR  RTO": "Hubli",
  "KOLAR  RTO": "Bangalore",
  "KOPPAL  RTO": "Hospet",
  "KRISHNARAJAPURAM  RTO": "Bangalore",
  "MADIKERI  RTO": "Mysore",
  "MANDYA  RTO": "Mysore",
  "MANGALORE  RTO": "Mangalore",
  "MYSURU WEST  RTO": "Mysore",
  "NAGAMANGALA  RTO": "Mysore",
  "NELAMANGALA  RTO": "Bangalore",
  "PUTTUR  RTO": "Mangalore",
  "RAICHUR  RTO": "Hospet",
  "RAMANAGAR  RTO": "Bangalore",
  "RAMDURGA ARTO": "Belgaum",
  "RANIBENNUR ARTO": "Hubli",
  "REGIONAL TRANSPORT OFFICE BELAGAVI": "Belgaum",
  "SAGAR  ARTO": "Shimoga",
  "SAKALESHPURA  ARTO": "Mangalore",
  "SHIMOGA  RTO": "Shimoga",
  "SIRSI  RTO": "Hubli",
  "TARIKERE, CHIKKAMAGALURU ARTO": "Mangalore",
  "TIPTUR  ARTO": "Tumkur",
  "TUMKUR  RTO": "Tumkur",
  "UDUPI  RTO": "Mangalore",
  "YADGIRI  RTO": "Kalaburagi",
  "YALAHANKA  RTO": "Bangalore",
  "ALUVA SRTO": "Ernakulam",
  "CHALAKKUDY SRTO": "Thrissur",
  "CHANGANACHERRY SRTO": "Kottayam",
  "CHENGANNUR SRTO": "Alappuzha",
  "CHERTHALA SRTO": "Alappuzha",
  "ERNAKULAM RTO": "Ernakulam",
  "IDUKKI RTO": "Ernakulam",
  "IRINJALAKUDA SRTO": "Thrissur",
  "IRITTY SRTO": "Kannur",
  "KAYAMKULAM SRTO": "Alappuzha",
  "KAZHAKUTTOM SRTO": "Thiruvananthapuram",
  "KODUNGALLUR SRTO": "Thrissur",
  "KOILANDY SRTO": "Kozhikode",
  "KONDOTTY SRTO": "Malappuram",
  "KONNI SRTO": "Kottayam",
  "KOTTARAKKARA SRTO": "Kollam",
  "KOTTAYAM RTO": "Kottayam",
  "KOZHIKODE RTO": "Kozhikode",
  "MANANTHAVADY SRTO": "Kozhikode",
  "MANNARGHAT SRTO": "Palakkad",
  "MATTANCHERRY SRTO": "Ernakulam",
  "MAVELIKKARA SRTO": "Alappuzha",
  "MUVATTUPUZHA RTO": "Ernakulam",
  "NANMANDA SRTO": "Kozhikode",
  "NEDUMANGADU SRTO": "Thiruvananthapuram",
  "NILAMBUR SRTO": "Malappuram",
  "NORTH PARUR SRTO": "Ernakulam",
  "PATTAMBI SRTO": "Palakkad",
  "PAYYANNUR SRTO": "Kannur",
  "PONNANI SRTO": "Malappuram",
  "RANNI SRTO": "Kottayam",
  "SULTHANBATHERY SRTO": "Kozhikode",
  "THALASSERY SRTO": "Kannur",
  "THODUPUZHA SRTO": "Ernakulam",
  "THRISSUR RTO": "Thrissur",
  "TRIPUNITHURA SRTO": "Ernakulam",
  "TRIVANDRUM RTO": "Thiruvananthapuram",
  "UDUMBANCHOLA SRTO": "Ernakulam",
  "VADAKARA RTO": "Kozhikode",
  "VAIKOM SRTO": "Kottayam",
  "WADAKKANCHERRY SRTO": "Thrissur",
  "WAYANAD RTO": "Kozhikode",
  "BAHOUR": "Pondicherry",
  "KARAIKAL": "Pondicherry",
  "MAHE": "Pondicherry",
  "OULGARET": "Pondicherry",
  "PUDUCHERRY": "Pondicherry",
  "VILLIANUR": "Pondicherry",
  "ALANGULAM UO": "Madurai AO",
  "AMBATTUR RTO": "Chennai",
  "ARAKKONAM UO": "Vellore",
  "ARANI RTO": "Vellore",
  "ARANTHANGI UO": "Thanjavur",
  "ARIYALUR RTO": "Tiruchirappalli",
  "ATTUR RTO": "Salem",
  "AVINASHI UO": "Coimbatore",
  "CHENGALPATTU RTO": "Chennai",
  "CHENNAI (CENTRAL) RTO": "Chennai",
  "CHENNAI (SOUTH) RTO": "Chennai",
  "CHENNAI (SOUTH-WEST) RTO": "Chennai",
  "CHENNAI (WEST) RTO": "Chennai",
  "CHEYYAR UO": "Vellore",
  "CHIDAMBARAM RTO": "Cuddalore",
  "COIMBATORE (CENTRAL) RTO": "Coimbatore",
  "COIMBATORE (NORTH) RTO": "Coimbatore",
  "COIMBATORE (SOUTH) RTO": "Coimbatore",
  "COIMBATORE (WEST) RTO": "Coimbatore",
  "CUDDALORE RTO": "Cuddalore",
  "DHARMAPURI RTO": "Krishnagiri",
  "ERODE (WEST) RTO": "Erode",
  "ERODE RTO": "Erode",
  "GINGEE UO": "Cuddalore",
  "GOPICHETTIPALAYAM RTO": "Erode",
  "GUDALORE UO": "Coimbatore",
  "HOSUR RTO": "Krishnagiri",
  "KALLAKURICHI RTO": "Cuddalore",
  "KANCHEEPURAM RTO": "Vellore",
  "KANGEYAM UO": "Coimbatore",
  "KARAIKUDI UO": "Madurai",
  "KOVILPATTI RTO": "Madurai AO",
  "KULITHALI UO": "Salem",
  "KUNDRATHUR RTO": "Chennai",
  "MADURAI (CENTRAL) RTO": "Madurai",
  "MADURAI (NORTH) RTO": "Madurai",
  "MADURANTAGAM UO": "Chennai",
  "MANMANGALAM UO": "Salem",
  "MANNARGUDI UO": "Thanjavur",
  "MARTHANDAM RTO": "Tirunelveli",
  "MAYILADUTHURAI RTO": "Thanjavur",
  "MEENAMBAKKAM RTO": "Chennai",
  "METTUPALAYAM RTO": "Coimbatore",
  "MUSURI UO": "Tiruchirappalli",
  "NAGERCOIL RTO": "Tirunelveli",
  "NAMAKKAL (NORTH) RTO": "Salem",
  "NAMAKKAL (SOUTH) RTO": "Salem",
  "NEYVELI UO": "Cuddalore",
  "OMALURE UO": "Salem",
  "OOTY RTO": "Coimbatore",
  "PALACODE UO": "Krishnagiri",
  "PANRUTI UO": "Cuddalore",
  "PARAMATHI VELLURE UO": "Salem",
  "PERAMBALUR RTO": "Tiruchirappalli",
  "PERUNDURAI RTO": "Erode",
  "POLLACHI RTO": "Coimbatore",
  "POONAMALLEE RTO": "Chennai",
  "PUDUKOTTAI RTO": "Thanjavur",
  "RAJAPALAYAM UO": "Madurai",
  "RAMANATHAPURAM RTO": "Madurai",
  "RANIPET RTO": "Vellore",
  "RASIPURAM UO": "Salem",
  "REDHILLS RTO": "Chennai",
  "RTO CHENNAI (NORTH WEST)": "Chennai",
  "SALEM (EAST) RTO": "Salem",
  "SALEM (SOUTH) RTO": "Salem",
  "SALEM (WEST) RTO": "Salem",
  "SANKAGIRI RTO": "Salem",
  "SANKARANKOVIL RTO": "Madurai AO",
  "SHOLINGANALLUR RTO": "Chennai",
  "SIRKALI UO": "Thanjavur",
  "SIVAGANGAI RTO": "Madurai",
  "SRIPERUMBUDUR RTO": "Chennai",
  "SULUR UO": "Coimbatore",
  "TAMBARAM RTO": "Chennai",
  "TENKASI RTO": "Madurai AO",
  "THANJAVUR RTO": "Thanjavur",
  "THIRUCHENDUR RTO": "Madurai AO",
  "THIRUKALUKUNTRAM UO": "Chennai",
  "THOOTHUKUDI RTO": "Madurai AO",
  "TIRUCHENGODE RTO": "Salem",
  "TIRUCHI RTO": "Tiruchirappalli",
  "TIRUNELVELI RTO": "Madurai AO",
  "TIRUPPUR (NORTH) RTO": "Coimbatore",
  "TIRUPPUR (SOUTH) RTO": "Coimbatore",
  "TIRUVANNAMALAI RTO": "Vellore",
  "TIRUVERANBUR UO": "Tiruchirappalli",
  "ULUNDURPET RTO": "Cuddalore",
  "VALLIYUR UO": "Madurai AO",
  "VANIYAMBADI RTO": "Vellore",
  "VELLORE RTO": "Vellore",
  "VILUPPURAM RTO": "Cuddalore",
  "VIRUDHACHALAM UO": "Cuddalore",
  "BAILHONGAL  RTO": "Belgaum",
  "CHINTAMANI ARTO": "Tumkur",
  "DANDELI ARTO": "Hubli",
  "MYSURU  EAST  RTO": "Mysore",
  "ANGAMALI SRTO": "Ernakulam",
  "ATTINGAL RTO": "Thiruvananthapuram",
  "GURUVAYUR SRTO": "Thrissur",
  "KANHANGAD SRTO": "Kannur",
  "KANNUR RTO": "Kannur",
  "KASARGODE RTO": "Kannur",
  "KOLLAM RTO": "Kollam",
  "KOTHAMANGALAM SRTO": "Ernakulam",
  "KUTTANADU SRTO": "Alappuzha",
  "MALAPPURAM RTO": "Malappuram",
  "MALLAPPALLY SRTO": "Kottayam",
  "NEYYATTINKARA SRTO": "Thiruvananthapuram",
  "OTTAPPALAM SRTO": "Palakkad",
  "PALAI SRTO": "Kottayam",
  "PARASSALA SRTO": "Thiruvananthapuram",
  "PERAMBRA SRTO": "Kozhikode",
  "PERINTHALMANNA SRTO": "Malappuram",
  "PERUMBAVUR SRTO": "Ernakulam",
  "RAMANATTUKARA (FEROKE) SRTO": "Kozhikode",
  "THALIPARAMBA SRTO": "Kannur",
  "THIRUR SRTO": "Malappuram",
  "THIRUVALLA SRTO": "Kottayam",
  "VARKALA SRTO": "Thiruvananthapuram",
  "ALANGUDI UO": "Thanjavur",
  "AMBASAMUTHIRAM UO": "Madurai AO",
  "ARUPPUKOTTAI UO": "Madurai",
  "BATLAGUNDU UO": "Tiruchirappalli",
  "BHAVANI UO": "Erode",
  "CHENNAI (NORTH) RTO": "Chennai",
  "CHENNAI (NORTH-EAST) RTO": "Chennai",
  "CHENNAI (SOUTH-EAST) RTO": "Chennai",
  "DHARAPURAM RTO": "Coimbatore",
  "DINDIGUL RTO": "Tiruchirappalli",
  "GUDIYATHAM UO": "Vellore",
  "GUMMIDIPOONDI UO": "Chennai",
  "HARUR UO": "Krishnagiri",
  "KARUR RTO": "Salem",
  "KUMBAKONAM RTO": "Thanjavur",
  "MADURAI (SOUTH) RTO": "Madurai",
  "MELUR UO": "Madurai",
  "METTUR RTO": "Salem",
  "PALANI RTO": "Tiruchirappalli",
  "PARAMAKUDI UO": "Madurai",
  "PATTUKOTTAI UNIT OFFICE": "Thanjavur",
  "SATHYAMANGALAM UO": "Erode",
  "SIVAKASI RTO": "Madurai",
  "SRIRANGAM RTO": "Tiruchirappalli",
  "SRIVILLIPUTHUR RTO": "Madurai",
  "THENI RTO": "Madurai",
  "THIRUPATTUR RTO": "Vellore",
  "THIRUTTANI UO": "Chennai",
  "THURAIYUR UO": "Tiruchirappalli",
  "TINDIVANAM RTO": "Cuddalore",
  "TIRUCHI(EAST) RTO": "Tiruchirappalli",
  "TIRUVALLUR RTO": "Chennai",
  "TIRUVARUR RTO": "Thanjavur",
  "UDUMALPET RTO": "Coimbatore",
  "VALAPPADI UO": "Salem",
  "ADOOR SRTO": "Kottayam",
  "ALAPPUZHA RTO": "Alappuzha",
  "ALATHUR SRTO": "Palakkad",
  "CHADAYAMANGALA SRTO": "Kollam",
  "CHITTUR SRTO": "Palakkad",
  "KANJIRAPPALLY SRTO": "Kottayam",
  "KARUNAGAPPALLY SRTO": "Kollam",
  "KATTAKADA SRTO": "Thiruvananthapuram",
  "KODUVALLY SRTO": "Kozhikode",
  "KUNNATHUR SRTO": "Kollam",
  "PATHANAMTHITTA RTO": "Kottayam",
  "PATHANAPURAM SRTO": "Kollam",
  "PUNALUR SRTO": "Kollam",
  "THIRURANGADI SRTO": "Malappuram",
  "THRIPRAYAR SRTO": "Thrissur",
  "UZHAVOOR SRTO": "Kottayam",
  "VELLARIKUNDU SRTO": "Kannur",
  "ARAVAKURICHI UO": "Salem",
  "CHENNAI (EAST) RTO": "Chennai",
  "ILLUPPUR UO": "Thanjavur",
  "KRISHNAGIRI RTO": "Krishnagiri",
  "KUMARAPALAYAM RTO": "Salem",
  "LALKUDI UO": "Tiruchirappalli",
  "NAGAPATTINAM RTO": "Thanjavur",
  "UTHAMAPALAYAM UO": "Madurai",
  "VIRUDHUNAGAR RTO": "Madurai",
  "MADHUGIRI, TUMAKURU ARTO": "Tumkur",
  "PALAKKAD RTO": "Palakkad",
  "VANDIPERIYAR SRTO": "Ernakulam",
  "AMBUR UO": "Vellore",
  "MANAPARAI UO": "Tiruchirappalli",
  "NATHAM UO": "Tiruchirappalli",
  "ODDANCHATRAM  UO": "Tiruchirappalli",
  "THIRUTHURAIPOONDI UO": "Thanjavur",
  "VADIPATTI UO": "Madurai",
  "VALPARAI UO": "Coimbatore",
  "DEVIKULAM SRTO": "Ernakulam",
  "YANAM": "Pondicherry",
  "THIRUMANGALAM  UO": "Madurai",
  "VEDACHANDUR UO": "Tiruchirappalli",
  "USILAMPATTI UO": "Madurai",
  "STU AND AUTORIKSHAW,  SHANTHINAGAR RTO": "Bangalore"
}

maker_short_mapping = {
  "MARUTI SUZUKI INDIA LTD": "Maruti",
  "HONDA CARS INDIA LTD": "Honda",
  "HYUNDAI MOTOR INDIA LTD": "Hyundai",
  "JSW MG MOTOR INDIA PVT LTD": "MG",
  "KIA INDIA PRIVATE LIMITED": "KIA",
  "MAHINDRA & MAHINDRA LIMITED": "Mahindra",
  "NISSAN MOTOR INDIA PVT LTD": "Nissan",
  "SKODA AUTO VOLKSWAGEN INDIA PVT LTD": "Skoda",
  "TATA MOTORS PASSENGER VEHICLES LTD": "Tata",
  "TATA PASSENGER ELECTRIC MOBILITY LTD": "Tata",
  "TOYOTA KIRLOSKAR MOTOR PVT LTD": "Toyota",
  "RENAULT INDIA PVT LTD": "Renault",
  "MAHINDRA ELECTRIC AUTOMOBILE LTD": "Mahindra",
  "STELLANTIS AUTOMOBILES INDIA PVT LTD": "PCA",
  "STELLANTIS INDIA PVT LTD": "Fiat",
  "BYD INDIA PRIVATE LIMITED": "BYD",
  "VINFAST AUTO INDIA PVT LTD": "Vinfast",
  "VOLKSWAGEN AG": "VW",
  "TATA MOTORS LTD": "Tata",
  "SKODA AUTO AS": "Skoda"
}


FUEL_GROUP_MAP = {
    "CNG": [
        "CNG ONLY",
        "PETROL/CNG",
        "PETROL(E20)/CNG"
    ],

    "Diesel": [
        "DIESEL"
    ],

    "Petrol": [
        "PETROL",
        "PETROL/ETHANOL"
    ],

    "EV": [
        "ELECTRIC(BOV)",
        "PURE EV"
    ],

    "Petrol-Hybrid": [
        "PETROL/HYBRID",
        "PETROL(E20)/HYBRID"
    ],

    "Diesel-Hybrid": [
        "DIESEL/HYBRID"
    ],

    "Strong-Hybrid": [
        "STRONG HYBRID EV"
    ]
}

fuel_lookup = {
    fuel: group
    for group, fuels in FUEL_GROUP_MAP.items()
    for fuel in fuels
}

def get_financial_year(date):
    if date.month >= 4:
        return f"{date.year}-{str(date.year + 1)[-2:]}"
    else:
        return f"{date.year - 1}-{str(date.year)[-2:]}"
    


def get_financial_quarter(date):
    if date.month in [4, 5, 6]:
        return "Q1"
    elif date.month in [7, 8, 9]:
        return "Q2"
    elif date.month in [10, 11, 12]:
        return "Q3"
    else:
        return "Q4"
def preprocess_master():
    df = pd.read_csv("final_master.csv")
    df = df.drop(columns=["scrape_timestamp"], errors="ignore")
    
    initial_total = None


    df = df.rename(columns={
        "Maker": "OEM",
        "timestamp": "Date"
    })
    df = df.drop(columns=["district"], errors="ignore")

    df["cluster"] = df["RTO"].map(cluster_mapping)
    df["cluster"] = df["cluster"].where(df["cluster"].notna(), None)
    missing_cluster_rtos = (
        df.loc[df["cluster"].isna(), "RTO"]
        .dropna()
        .unique()
        .tolist()
    )
    if missing_cluster_rtos:
        print("Missing cluster mapping for RTOs:", missing_cluster_rtos)


    df["Date"] = pd.to_datetime(df["Date"], dayfirst=True, format="mixed",errors="raise")
    df["city"] = df["RTO"].map(city_mapping)
    df["AO"] = df["RTO"].map(rto_ao_mapping)
    df["maker_short"] = df["OEM"].map(maker_short_mapping)
    

    missing_ao_count = df["AO"].isna().sum()
    if missing_ao_count > 0:
        print(f"Warning: {missing_ao_count} rows have missing AO mapping")

    id_cols = [
        "Date", "state","cluster","city","AO","RTO",
        "rto_number", "vehicle_type",
         "OEM", "maker_short"
    ]

    fuel_cols = [c for c in df.columns if c not in id_cols and c != "TOTAL"]
    initial_total = df[fuel_cols].sum().sum()


    out = df.melt(
        id_vars=id_cols,
        value_vars=fuel_cols,
        var_name="FuelType",
        value_name="Regn Vol"
    )

    out["Regn Vol"] = pd.to_numeric(out["Regn Vol"], errors="coerce").fillna(0)
    out = out[out["Regn Vol"] != 0]
    
    total_after_melt = out["Regn Vol"].sum()


    out["FuelGroup"] = out["FuelType"].map(fuel_lookup)
    missing_fuel_count = out["FuelGroup"].isna().sum()
    missing_fuel_volume = out[out["FuelGroup"].isna()]["Regn Vol"].sum()
    if missing_fuel_count > 0:
        print(f"Warning: {missing_fuel_count} rows have unmapped FuelTypes (volume: {missing_fuel_volume})")
    out = out.dropna(subset=["FuelGroup"])
    
    total_after_fuel_mapping = out["Regn Vol"].sum()


    grouped = (
        out
        .groupby(id_cols + ["FuelGroup"], dropna=False, as_index=False)["Regn Vol"]
        .sum()
    )
    
    final_total = grouped["Regn Vol"].sum()
    
    # Report data tracking
    if initial_total is not None:
        print(f"Data tracking: Initial={initial_total}, After melt={total_after_melt}, After fuel mapping={total_after_fuel_mapping}, Final={final_total}")
        difference = initial_total - final_total
        if abs(difference) > 0.01:
            if difference > 0:
                print(f"WARNING: Data loss detected! Lost {difference:.2f} values")
            else:
                print(f"WARNING: Data gain detected! Gained {abs(difference):.2f} values (TOTAL column may be incorrect in source data)")
        else:
            print("Data integrity: All values preserved")

    grouped["Zone"] = grouped["state"].map({
        "Karnataka": "S1",
        "Tamil Nadu": "S2",
        "Puducherry": "S2",
        "Kerala": "S3"
    })

    grouped["FY"] = grouped["Date"].apply(get_financial_year)
    grouped["month"] = grouped["Date"].dt.strftime("%B")
    grouped["Qtr"] = grouped["Date"].apply(get_financial_quarter)

    grouped.to_csv("master_preprocessed.csv", index=False)
    # grouped.to_csv("AfterTest.csv", index=False)

    print("Saved:", grouped.shape, "-> master_preprocessed.csv")

if __name__ == "__main__":

    preprocess_master()
